### ISSUE TITLE
Bounds on fitting parameters

### ISSUE THREAD

**Issue by meoat33** [Spinmob/spinmob#100]
It would be good to be able to set the bounds on fitting parameters, like it is possible in scipy.optimize.curve_fit.

Is there an obvious way to do so using scipy.optimize.leastsq?

**Comment by jaxankey** [comment]
Not that I know of. We could in principle switch the back end from leastsq to curve_fit. I think.

Anyone want to try this? If so, maybe make a _fitter() class in the short term so we can test them against each other (and not expose users to it while we dev it.

**Comment by jaxankey** [comment]
Probably the best way to do this is to use lmfit, which allows arbitrary constraints (constraints that can depend on the other fit parameters, even!). I have a working concept and might try to replace the engine under fitter() with it.

**Comment by jaxankey** [comment]
Should be working in the latest commit. I need to write some tests for it.
