### ISSUE TITLE
Clean up _tweaks.py

### ISSUE THREAD

**Issue by jaxankey** [Spinmob/spinmob#29]
There is a LOT of > 10 year-old code in this file. We should comb over it while writing tests and eliminate silly / useless functions.

**Comment by jayich** [comment]
@jaxankey , I don't see the module _tweaks.py.

**Comment by jaxankey** [comment]
Pylab tweaks

-Jack

Sent from sender's phone with typos. Sender not liable for inflammatory
autocorrects.

**Comment by jayich** [comment]
https://github.com/Spinmob/spinmob/blob/master/_pylab_tweaks.py
