### ISSUE TITLE
delimiter setting

### ISSUE THREAD

**Issue by jayich** [Spinmob/spinmob#36]
Ability to do 

sm.settings['delimiter'] = ','

so that the default limiter is CSV, for example.

**Comment by jaxankey** [comment]
Does this matter any more with auto-detection?

**Comment by jayich** [comment]
@jaxankey , auto-detection has been added?  If that is the case we should close this.  I guess the best would be to add a bit of test code for a CSV delimited file, for example.

**Comment by jayich** [comment]
closed via https://github.com/Spinmob/spinmob/issues/79
