### ISSUE TITLE
load databox with a single line of data

### ISSUE THREAD

**Issue by jayich** [Spinmob/spinmob#55]
Hitting an error when loading a file that has a single element for each column of data.  I'm printing what looks like relevant information in this branch: https://github.com/Spinmob/spinmob/tree/load_single_line_of_data

**Comment by jaxankey** [comment]
Send me a test file?

**Comment by jayich** [comment]
@jaxankey , see this commit: https://github.com/Spinmob/spinmob/commit/694abc0d92c55c92c4f2200bcccb45322229919d

**Comment by jaxankey** [comment]
Man, you can put all test stuff straight into the master branch. It won't
break anything for the users.
