### ISSUE TITLE
plot_guess_zoom not working reliably

### ISSUE THREAD

**Issue by jayich** [Spinmob/spinmob#64]
When setting plot_guess_zoom=True it does not appear to change the plot to show the guess.

**Comment by jaxankey** [comment]
Maybe you have to run plot() again? Can you make a test?

**Comment by jayich** [comment]
@jaxankey , anything graphical gets difficult to test.  Generally there are ways to make graphical tests, matplotlib for example is nearly 100% tested (I think).  I will close this as a I won't get to this anytime soon, but if this comes up again I will look into getting matplotlib type tests integrated into spinmob.

**Comment by jaxankey** [comment]
Well, as a hack, I've added tests for things like dialogs, with the titles
of the dialogs telling you what to do, then verifying the result. It takes
longer but at least leaves me feeling warm and fuzzy that nothing is
broken. We could do something similar for the fitter / plotting. Or we
could make a "test / demo suite" like pyqtgraph's "examples.run()"

**Comment by jayich** [comment]
I haven't looked at pyqtgraph's examples.run().  That sounds manual?  For matplotlib I know that they basically have a collection of image files and all of the tests generate plots and compare to the image files automatically.  

I guess something (manual) is better than nothing (I have been meaning to implement plot tests in spinmob and lab code now for years...)

**Comment by jaxankey** [comment]
Good luck having time for that, Professor Jayich.

**Comment by jayich** [comment]
Oh I know, I know.  @jaxankey 

If only...
