### ISSUE TITLE
automatically select previously selected files

### ISSUE THREAD

**Issue by jayich** [Spinmob/spinmob#65]
When you load a file into a databox it would be great if the previously selected files were highlighted (in addition to spinmob opening up the directory where files were previously selected).

**Comment by jaxankey** [comment]
Is that even possible with Qt dialogs? Let me know if it is and I'll see if it's feasible to implement. I think this would go in the settings file, but that would make the settings file a bit bigger (not the end of the world).

**Comment by jayich** [comment]
The answer is no:  http://stackoverflow.com/questions/37805442/does-qt-support-open-a-folder-and-highlight-a-particular-file
