### ISSUE TITLE
fitter with multiple functions require functions with placeholder arguments

### ISSUE THREAD

**Issue by jayich** [Spinmob/spinmob#66]
In order to use functions in the fitter the functions require each parameter in the function definition.  This means to get the default fitting to work with function you need the following code:

``` python
def cosine_function(x, a, b, c):
    """
    a*x*cos(b*x)+c
    """
    return a*x*_n.cos(b*x)+c

def linear_function(x, a, b, c):
    """
    a*x+c
    """    
    return a*x+c

f = sm.data.fitter(f=[cosine_function, linear_function])
f.set_data(xdata=[1, 2, 3, 4, 5], ydata=[[1, 2, 1, 2, 1], [3, 2, 3, 4, 3]])
f.fit()
```

Instead of defining the linear function with

``` python
linear_function(x, a, c)
```

This does not scale up nicely if you want to simultaneously fit 10 data sets where one parameter is varied, for example.  It would be great to feed each function only its particular required parameters.

**Comment by jayich** [comment]
I guess the main problem is that for multiple data sets that you want to fit simultaneously with one parameter varying you have to redefine the nominally exact same function multiple times, and sort out the varying parameter accordingly.

**Comment by jayich** [comment]
I feel like one potential solution here would be to send in a list of parameter strings for the independent function fitting parameter.  The shared fitting parameters could go in the usual place.  Thoughts?

**Comment by jaxankey** [comment]
Just stringify your functions? Or if you want to code something else, go for it.
