### ISSUE TITLE
databox.save_data(force_overwrite=True) may fail when file exists?

### ISSUE THREAD

**Issue by jaxankey** [Spinmob/spinmob#71]
Unconfirmed

**Comment by jayich** [comment]
I tried this on OSX 10.11.4.  I the OS did the overwrite.  When I selected the file to overwrite a system prompt to overwrite the file popped up and from there I could choose whether to overwrite.  I tried both options in the prompt.

**Comment by jaxankey** [comment]
Maybe if the file is open / locked?

**Comment by jayich** [comment]
Clarification: the file was closed and not locked in my brief test above.

Ideally we don't want any prompt to appear when settting force_overwrite=True, right?  That seems ideal to me.

**Comment by jaxankey** [comment]
It was more meant to be used when specifying the path, not going through
the dialog. I guess you could set the dialog to not ask the question, but
if you're already clicking around there isn't much time to save (and you
might mis-click accidentally and delete something important, which will not
appear in the recycle bin).

**Comment by jayich** [comment]
The operating system has dialog that pops up in response to potentially overwriting a file.

**Comment by jaxankey** [comment]
Yes, so it's a question of whether we want "force overwrite" to affect this
behavior. The "force overwrite" option is intended for scripted saving
without the GUI.

**Comment by jayich** [comment]
I'm in favor of force_overwrite affecting this behavior.  I imagine it could be difficult to bypass the system dialog on overwriting files.

Here is some type of solution:

http://stackoverflow.com/questions/8107352/force-overwrite-in-os-rename

It involves another module dependency, which is annoying.

**Comment by jaxankey** [comment]
Isn't there just a flag in the save dialog to not warn?
