### ISSUE TITLE
new change to fix breaks old code

### ISSUE THREAD

**Issue by jayich** [Spinmob/spinmob#73]
@jaxankey , it would be nice to know what this commit fixes and how I should change working with the fitter to adapt.

https://github.com/Spinmob/spinmob/commit/dc9a87324aee275c8430c2efd7ffaf1c861bba1b

It breaks code such as the below:

```python
xdata = self.detunings
ydata = self.blue_counts
eydata = self.blue_count_errs

self.fitter.set_data(xdata=xdata, ydata=ydata, eydata=eydata)
self.fitter.fit()
```

This was most likely unintended.  I'll get to adding a test for this once I understand it better.  If this behavior is unintended it would be great to make a fix that handles the case that the most recent commit has fixed and allows us to work with code such as the above.  

Here is the error I get for reference:

```python
  1525             return self._error("No data. Please use set_data() prior to fitting.")
   1526 
-> 1527         if (_n.concatenate(self._eydata_massaged)==0).any():
   1528             return self._error("One or more of your error bars is zero! Are you trying to make me divide by zero? Answer the question.")
   1529 

TypeError: The first input argument needs to be a sequence
```

**Comment by jaxankey** [comment]
Arg. The whole point of that line of code is just to check if any of the
eydata is zero, and it has to cover a lot of situations. It's aimed at
undergraduates to keep them from not knowing why stuff breaks.

If you can find a more general way to catch everything go for it, otherwise
let's just comment it out (and mention it's buggy in a comment near it).

Or we could just remove it entirely.

**Comment by jayich** [comment]
@jaxankey , okay, good deal.  I just worked on the previous commit.  I'll submit a PR today.  Maybe I can fix it a bit.

**Comment by jayich** [comment]
PR: https://github.com/Spinmob/spinmob/pull/74

**Comment by jayich** [comment]
closed via: https://github.com/Spinmob/spinmob/pull/74
