### ISSUE TITLE
Trailing white space when loading should be ignored

### ISSUE THREAD

**Issue by jayich** [Spinmob/spinmob#75]
I submit a test to confirm, but I believe trailing white space in a file can cause an error when loading.  Unless there is something I'm not thinking of here databox files should just load regardless of trailing white space.

**Comment by jaxankey** [comment]
I haven't seen this. Can you add it to the test with a file that kills it? This definitely used to work.

Without knowing what conditions it is, it could have to do with the delimiter detection, which looks at the last line of the file first to see what method of splitting gives just numbers.

**Comment by jayich** [comment]
@jaxankey , I will identify this problem with test code, and from there hopefully come up with a fix.

**Comment by jayich** [comment]
Fixture in this commit will not plot due to a column error with the last line:  https://github.com/Spinmob/spinmob/commit/42577ec3f806d7ba05ca74a267d5659451107f25
