### ISSUE TITLE
Add a requirements.txt file

### ISSUE THREAD

**Issue by jayich** [Spinmob/spinmob#85]
All pip installable dependencies should be in requirements.txt so that the single command

```bash
$ pip install -r /path/to/requirements.txt
```
installs all pipable modules.

dependencies:  
pyqtgraph

note: with Anaconda all that needs to be installed is pyqtgraph

**Comment by jaxankey** [comment]
Go for it. You could add the other dependencies; does pip ignore them if conda already installed them?

**Comment by jaxankey** [comment]
I'm also worried that if we do this, there will be conflicts between conda and pip installations. Also, I do not want people to *have* to install pyqtgraph. It will warn about it, but if you don't use egg you don't need it.
