### ISSUE TITLE
How to use errors in x values when calculating fit and reduced chi^2?

### ISSUE THREAD

**Issue by MilesCranmer** [Spinmob/spinmob#88]
Hi,

I was wondering if there is a way to use errors in the x values when calculating fit and reduced chi^2? Right now I let the fit run with just the y errors, then I use the fit to transfer x errors to the y errors (e.g., for y=ax+b, I take ey^2 <- ey^2 + a^2 ex^2 after calculating a). Is there a better way to do this?

Cheers,

Miles

**Comment by jayich** [comment]
Currently the fitter does not handle x errors.  

https://github.com/Spinmob/spinmob/blob/master/_data.py#L909

Contributing this functionality is welcomed.

**Comment by jaxankey** [comment]
Yeah, this requires a switch to ODR if x-errors are specified. The thing holding this up is ODR doesn't provide access to its orthogonal residuals to my knowledge. If we can get access to this, I'm game!
