### ISSUE TITLE
delete _constants.py?

### ISSUE THREAD

**Issue by jayich** [Spinmob/spinmob#91]
Is this module used?

https://github.com/Spinmob/spinmob/blob/master/_constants.py

**Comment by jayich** [comment]
@jaxankey I would like to cu _constants.py.  Thoughts?

**Comment by jaxankey** [comment]
Make sure it's not used (imported?) by any other files first, but yeah.

**Comment by jayich** [comment]
I checked, _constants.py is not used in spinmob.

**Comment by jaxankey** [comment]
Kill it?
